
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 12 11:53:07 CST 2012
//----------------------------------------------------

package javac.parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int DIVIDE = 37;
  public static final int STRING_LITERAL = 43;
  public static final int LBRACKET = 22;
  public static final int CHAR = 7;
  public static final int INTEGER = 41;
  public static final int LPAREN = 19;
  public static final int GREATER = 32;
  public static final int CONTINUE = 15;
  public static final int INT = 5;
  public static final int MINUS = 35;
  public static final int LESS = 30;
  public static final int FOR = 12;
  public static final int CHARACTER = 44;
  public static final int RPAREN = 20;
  public static final int NOT = 39;
  public static final int SEMICOLON = 16;
  public static final int AND = 27;
  public static final int RECORD = 3;
  public static final int OR = 26;
  public static final int COMMA = 21;
  public static final int MULTIPLY = 36;
  public static final int PLUS = 34;
  public static final int ASSIGN = 25;
  public static final int IF = 9;
  public static final int ID = 42;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int RBRACKET = 23;
  public static final int NEW = 4;
  public static final int error = 1;
  public static final int MODULO = 38;
  public static final int NULL = 8;
  public static final int NEQ = 29;
  public static final int BREAK = 14;
  public static final int EQ = 28;
  public static final int LBRACE = 17;
  public static final int NATIVE = 2;
  public static final int ELSE = 10;
  public static final int WHILE = 11;
  public static final int LESS_EQ = 31;
  public static final int RBRACE = 18;
  public static final int STRING = 6;
  public static final int LRBRACKET = 24;
  public static final int GREATER_EQ = 33;
}

