/* The following code was generated by JFlex 1.4.3 on 12-3-30 ÏÂÎç7:36 */

package javac.parser;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12-3-30 ÏÂÎç7:36 from the specification file
 * <tt>D:/jflex/javac.flex</tt>
 */
class Yylex implements java_cup.runtime.Scanner, Symbols {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYCOMMENT = 6;
  public static final int YYSTRING = 2;
  public static final int YYINITIAL = 0;
  public static final int YYCHAR = 4;
  public static final int YYLINECOMMENT = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\1\1\0\1\6\1\2\22\0\1\6\1\50\1\56"+
    "\2\0\1\55\1\51\1\57\1\34\1\35\1\10\1\53\1\43\1\54"+
    "\1\44\1\7\1\5\11\4\1\0\1\42\1\45\1\46\1\47\2\0"+
    "\32\3\1\40\1\60\1\41\1\0\1\3\1\0\1\21\1\32\1\25"+
    "\1\27\1\13\1\12\1\30\1\17\1\11\1\3\1\33\1\14\1\3"+
    "\1\20\1\26\2\3\1\24\1\15\1\22\1\31\1\23\1\16\3\3"+
    "\1\36\1\52\1\37\u05e2\0\12\61\206\0\12\61\u026c\0\12\61\166\0"+
    "\12\61\166\0\12\61\166\0\12\61\166\0\12\61\167\0\11\61\166\0"+
    "\12\61\166\0\12\61\166\0\12\61\340\0\12\61\166\0\12\61\106\0"+
    "\12\61\u0116\0\12\61\u031f\0\11\61\u046e\0\12\61\46\0\12\61\u012c\0"+
    "\12\61\ue5c0\0\12\61\346\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\2\2\1\3\2\4\1\5\1\6\11\3"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\2\1\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\2\32\1\33\1\31\1\0"+
    "\2\34\1\0\2\2\2\35\1\36\1\37\1\40\14\3"+
    "\1\0\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\2\50\1\51\1\52\1\53\1\54\1\55\1\56\6\50"+
    "\1\56\1\50\1\57\1\60\1\61\1\62\3\3\1\63"+
    "\7\3\2\0\1\64\1\65\1\66\1\67\1\70\1\71"+
    "\1\72\1\73\3\3\1\74\2\3\1\75\2\3\1\76"+
    "\1\0\1\3\1\77\4\3\1\100\1\101\1\102\1\103"+
    "\1\104\1\105\2\3\1\106";

  private static int [] zzUnpackAction() {
    int [] result = new int[145];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\372\0\u012c"+
    "\0\u015e\0\u0190\0\372\0\u01c2\0\372\0\u01f4\0\u0226\0\u0258"+
    "\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\372\0\372"+
    "\0\372\0\372\0\u03b6\0\372\0\372\0\372\0\372\0\u03e8"+
    "\0\u041a\0\u044c\0\u047e\0\u04b0\0\u04e2\0\372\0\372\0\372"+
    "\0\372\0\372\0\372\0\372\0\u0514\0\372\0\u0546\0\u0578"+
    "\0\372\0\u05aa\0\u05dc\0\u060e\0\u0640\0\372\0\u0672\0\372"+
    "\0\372\0\u015e\0\u06a4\0\u06d6\0\u0708\0\u073a\0\u076c\0\u079e"+
    "\0\u07d0\0\u0802\0\u0834\0\u0866\0\u0898\0\u08ca\0\u03b6\0\372"+
    "\0\372\0\372\0\372\0\372\0\372\0\372\0\372\0\u08fc"+
    "\0\372\0\372\0\372\0\372\0\372\0\372\0\u092e\0\u0960"+
    "\0\u0992\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\372\0\372"+
    "\0\u015e\0\u015e\0\u0abe\0\u0af0\0\u0b22\0\u015e\0\u0b54\0\u0b86"+
    "\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e\0\u0c80\0\u0cb2\0\u0ce4\0\372"+
    "\0\372\0\372\0\372\0\372\0\372\0\372\0\u015e\0\u0d16"+
    "\0\u0d48\0\u0d7a\0\u015e\0\u0dac\0\u0dde\0\u015e\0\u0e10\0\u0e42"+
    "\0\372\0\u0e74\0\u0ea6\0\u015e\0\u0ed8\0\u0f0a\0\u0f3c\0\u0f6e"+
    "\0\u015e\0\372\0\u015e\0\u015e\0\u015e\0\u015e\0\u0fa0\0\u0fd2"+
    "\0\u015e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[145];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\7\1\14"+
    "\1\15\1\16\1\17\1\20\1\11\1\21\1\22\1\11"+
    "\1\23\3\11\1\24\1\25\4\11\1\26\1\11\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\2\6\1\53\1\54\1\55\53\53"+
    "\1\56\1\53\1\57\1\53\1\60\1\61\1\62\55\60"+
    "\1\63\1\60\7\7\1\64\1\65\52\7\1\66\1\67"+
    "\57\7\63\0\1\7\63\0\3\11\3\0\23\11\32\0"+
    "\2\12\63\0\1\70\1\71\54\0\3\11\3\0\1\11"+
    "\1\72\5\11\1\73\13\11\31\0\3\11\3\0\15\11"+
    "\1\74\5\11\31\0\3\11\3\0\3\11\1\75\17\11"+
    "\31\0\3\11\3\0\11\11\1\76\11\11\31\0\3\11"+
    "\3\0\6\11\1\77\14\11\31\0\3\11\3\0\2\11"+
    "\1\100\5\11\1\101\7\11\1\102\2\11\31\0\3\11"+
    "\3\0\2\11\1\103\20\11\31\0\3\11\3\0\6\11"+
    "\1\104\6\11\1\105\5\11\31\0\3\11\3\0\13\11"+
    "\1\106\7\11\27\0\2\107\3\0\1\107\32\0\1\110"+
    "\66\0\1\111\61\0\1\112\61\0\1\113\61\0\1\114"+
    "\64\0\1\115\62\0\1\116\10\0\1\54\60\0\1\117"+
    "\1\0\2\117\2\120\12\117\1\121\1\117\1\122\1\117"+
    "\1\123\31\117\1\124\1\117\1\125\1\120\57\0\1\126"+
    "\3\0\1\61\60\0\1\117\1\0\2\117\2\127\4\117"+
    "\1\130\5\117\1\131\1\117\1\132\1\117\1\133\5\117"+
    "\1\134\24\117\1\135\1\136\1\127\10\0\1\137\60\0"+
    "\1\140\53\0\1\66\63\0\3\11\3\0\11\11\1\141"+
    "\11\11\31\0\3\11\3\0\13\11\1\142\7\11\31\0"+
    "\3\11\3\0\4\11\1\143\16\11\31\0\3\11\3\0"+
    "\13\11\1\144\7\11\31\0\3\11\3\0\1\145\22\11"+
    "\31\0\3\11\3\0\5\11\1\146\15\11\31\0\3\11"+
    "\3\0\11\11\1\147\11\11\31\0\3\11\3\0\3\11"+
    "\1\150\17\11\31\0\3\11\3\0\11\11\1\151\2\11"+
    "\1\152\6\11\31\0\3\11\3\0\10\11\1\153\12\11"+
    "\31\0\3\11\3\0\7\11\1\154\13\11\31\0\3\11"+
    "\3\0\2\11\1\155\20\11\32\0\2\156\53\0\1\156"+
    "\4\0\2\157\53\0\1\157\57\0\1\160\61\0\1\161"+
    "\61\0\1\162\61\0\1\163\61\0\1\164\61\0\1\165"+
    "\61\0\1\166\5\0\3\11\3\0\2\11\1\167\20\11"+
    "\31\0\3\11\3\0\1\170\22\11\31\0\3\11\3\0"+
    "\3\11\1\171\17\11\31\0\3\11\3\0\1\172\22\11"+
    "\31\0\3\11\3\0\3\11\1\173\17\11\31\0\3\11"+
    "\3\0\20\11\1\174\2\11\31\0\3\11\3\0\15\11"+
    "\1\175\5\11\31\0\3\11\3\0\13\11\1\176\7\11"+
    "\31\0\3\11\3\0\11\11\1\177\11\11\31\0\3\11"+
    "\3\0\10\11\1\200\12\11\32\0\2\201\53\0\1\201"+
    "\4\0\2\202\53\0\1\202\3\0\3\11\3\0\7\11"+
    "\1\203\13\11\31\0\3\11\3\0\2\11\1\204\20\11"+
    "\31\0\3\11\3\0\12\11\1\205\10\11\31\0\3\11"+
    "\3\0\13\11\1\206\7\11\31\0\3\11\3\0\13\11"+
    "\1\207\7\11\31\0\3\11\3\0\1\210\22\11\31\0"+
    "\3\11\3\0\22\11\1\211\105\0\1\212\5\0\3\11"+
    "\3\0\17\11\1\213\3\11\31\0\3\11\3\0\2\11"+
    "\1\214\20\11\31\0\3\11\3\0\7\11\1\215\13\11"+
    "\31\0\3\11\3\0\16\11\1\216\4\11\31\0\3\11"+
    "\3\0\7\11\1\217\13\11\31\0\3\11\3\0\20\11"+
    "\1\220\2\11\31\0\3\11\3\0\2\11\1\221\20\11"+
    "\26\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4100];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\2\11\3\1\1\11\1\1\1\11\11\1\4\11"+
    "\1\1\4\11\6\1\7\11\1\1\1\11\1\1\1\0"+
    "\1\11\1\1\1\0\2\1\1\11\1\1\2\11\15\1"+
    "\1\0\10\11\1\1\6\11\10\1\2\11\15\1\2\0"+
    "\7\11\12\1\1\11\1\0\7\1\1\11\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[145];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private StringBuffer string = new StringBuffer();
    private int commentCount = 0;

    private void err(String message) {
        System.err.println(String.format("Scanning error in line %d, column %d: %s", yyline + 1, yycolumn + 1, message));
    }

    private java_cup.runtime.Symbol tok(int kind) {
        return new java_cup.runtime.Symbol(kind, yyline, yycolumn);
    }

    private java_cup.runtime.Symbol tok(int kind, Object value) {
        return new java_cup.runtime.Symbol(kind, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 208) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 16: 
          { return tok(LESS);
          }
        case 71: break;
        case 24: 
          { yybegin(YYCHAR);
          }
        case 72: break;
        case 33: 
          { return tok(LRBRACKET);
          }
        case 73: break;
        case 7: 
          { return tok(LPAREN);
          }
        case 74: break;
        case 13: 
          { return tok(SEMICOLON);
          }
        case 75: break;
        case 28: 
          { err("Unterminated character literal at end of line ");
          }
        case 76: break;
        case 46: 
          { yybegin(YYINITIAL); return tok(CHARACTER, new Character(yytext().charAt(0)));
          }
        case 77: break;
        case 64: 
          { return tok(BREAK);
          }
        case 78: break;
        case 63: 
          { return tok(WHILE);
          }
        case 79: break;
        case 59: 
          { return tok(ELSE);
          }
        case 80: break;
        case 10: 
          { return tok(RBRACE);
          }
        case 81: break;
        case 15: 
          { return tok(DOT);
          }
        case 82: break;
        case 18: 
          { return tok(GREATER);
          }
        case 83: break;
        case 4: 
          { return tok(INTEGER, Integer.valueOf(yytext()));
          }
        case 84: break;
        case 42: 
          { string.append( '\t' );
          }
        case 85: break;
        case 48: 
          { if (--commentCount == 0) yybegin(YYINITIAL);
          }
        case 86: break;
        case 62: 
          { char val = (char) Integer.parseInt(yytext().substring(1)); string.append( val );
          }
        case 87: break;
        case 61: 
          { return tok(CHAR);
          }
        case 88: break;
        case 21: 
          { return tok(MINUS);
          }
        case 89: break;
        case 5: 
          { return tok(DIVIDE);
          }
        case 90: break;
        case 29: 
          { yybegin(YYINITIAL);
          }
        case 91: break;
        case 23: 
          { yybegin(YYSTRING); string.setLength(0);
          }
        case 92: break;
        case 66: 
          { return tok(STRING);
          }
        case 93: break;
        case 49: 
          { return tok(INT);
          }
        case 94: break;
        case 1: 
          { err("Illegal character " + yytext());
          }
        case 95: break;
        case 6: 
          { return tok(MULTIPLY);
          }
        case 96: break;
        case 38: 
          { return tok(AND);
          }
        case 97: break;
        case 19: 
          { return tok(NOT);
          }
        case 98: break;
        case 40: 
          { err("Illegal escape sequence \""+yytext()+"\"");
          }
        case 99: break;
        case 55: 
          { yybegin(YYINITIAL); return tok(CHARACTER, new Character('\r'));
          }
        case 100: break;
        case 58: 
          { yybegin(YYINITIAL); return tok(CHARACTER, new Character('\\'));
          }
        case 101: break;
        case 14: 
          { return tok(COMMA);
          }
        case 102: break;
        case 30: 
          { yybegin(YYLINECOMMENT);
          }
        case 103: break;
        case 67: 
          { return tok(NATIVE);
          }
        case 104: break;
        case 70: 
          { return tok(CONTINUE);
          }
        case 105: break;
        case 11: 
          { return tok(LBRACKET);
          }
        case 106: break;
        case 32: 
          { return tok(IF);
          }
        case 107: break;
        case 53: 
          { yybegin(YYINITIAL); return tok(CHARACTER, new Character('\n'));
          }
        case 108: break;
        case 8: 
          { return tok(RPAREN);
          }
        case 109: break;
        case 39: 
          { return tok(OR);
          }
        case 110: break;
        case 35: 
          { return tok(EQ);
          }
        case 111: break;
        case 60: 
          { return tok(NULL);
          }
        case 112: break;
        case 22: 
          { return tok(MODULO);
          }
        case 113: break;
        case 27: 
          { yybegin(YYINITIAL); return tok(STRING_LITERAL, string.toString());
          }
        case 114: break;
        case 37: 
          { return tok(NEQ);
          }
        case 115: break;
        case 44: 
          { string.append( '\"' );
          }
        case 116: break;
        case 9: 
          { return tok(LBRACE);
          }
        case 117: break;
        case 31: 
          { yybegin(YYCOMMENT); commentCount++;
          }
        case 118: break;
        case 52: 
          { yybegin(YYINITIAL); return tok(CHARACTER, new Character('\f'));
          }
        case 119: break;
        case 34: 
          { return tok(LESS_EQ);
          }
        case 120: break;
        case 12: 
          { return tok(RBRACKET);
          }
        case 121: break;
        case 43: 
          { string.append( '\r' );
          }
        case 122: break;
        case 45: 
          { string.append( '\\' );
          }
        case 123: break;
        case 17: 
          { return tok(ASSIGN);
          }
        case 124: break;
        case 47: 
          { commentCount++;
          }
        case 125: break;
        case 56: 
          { yybegin(YYINITIAL); return tok(CHARACTER, new Character('\b'));
          }
        case 126: break;
        case 69: 
          { return tok(RECORD);
          }
        case 127: break;
        case 68: 
          { return tok(RETURN);
          }
        case 128: break;
        case 50: 
          { return tok(FOR);
          }
        case 129: break;
        case 26: 
          { err("Unterminated string at end of line ");
          }
        case 130: break;
        case 65: 
          { yybegin(YYINITIAL); return tok(CHARACTER, new Character((char)Integer.parseInt(yytext().substring(1,4))));
          }
        case 131: break;
        case 41: 
          { string.append( '\n' );
          }
        case 132: break;
        case 54: 
          { yybegin(YYINITIAL); return tok(CHARACTER, new Character('\t'));
          }
        case 133: break;
        case 57: 
          { yybegin(YYINITIAL); return tok(CHARACTER, new Character('\''));
          }
        case 134: break;
        case 51: 
          { return tok(NEW);
          }
        case 135: break;
        case 25: 
          { string.append( yytext() );
          }
        case 136: break;
        case 36: 
          { return tok(GREATER_EQ);
          }
        case 137: break;
        case 20: 
          { return tok(PLUS);
          }
        case 138: break;
        case 3: 
          { return tok(ID, yytext());
          }
        case 139: break;
        case 2: 
          { 
          }
        case 140: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return tok(EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
